/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameControl from "./GameControl"
import GameUI from "./GameUI"
import GameResultUI from "./GameResultUI"
import test from "./test"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="bubble/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("GameControl.ts",GameControl);
        reg("GameUI.ts",GameUI);
        reg("GameResultUI.ts",GameResultUI);
        reg("test.ts",test);
    }
}
GameConfig.init();