/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ScaleButton from "./common/ScaleButton"
import LaunchControl from "./control/LaunchControl"
import Resize from "./common/Resize"
import LoadingUI from "./view/LoadingUI"
import GameUI from "./view/GameUI"
import GameResultUI from "./view/GameResultUI"
import GameControl from "./control/GameControl"
import SelectControl from "./control/SelectControl"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="bubble/LaunchScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("common/ScaleButton.ts",ScaleButton);
        reg("control/LaunchControl.ts",LaunchControl);
        reg("common/Resize.ts",Resize);
        reg("view/LoadingUI.ts",LoadingUI);
        reg("view/GameUI.ts",GameUI);
        reg("view/GameResultUI.ts",GameResultUI);
        reg("control/GameControl.ts",GameControl);
        reg("control/SelectControl.ts",SelectControl);
    }
}
GameConfig.init();