/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ScaleButton from "./common/ScaleButton"
import Launch from "./Launch"
import Resize from "./common/Resize"
import GameUI from "./GameUI"
import GameResultUI from "./GameResultUI"
import GameControl from "./GameControl"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="bubble/LaunchScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("common/ScaleButton.ts",ScaleButton);
        reg("Launch.ts",Launch);
        reg("common/Resize.ts",Resize);
        reg("GameUI.ts",GameUI);
        reg("GameResultUI.ts",GameResultUI);
        reg("GameControl.ts",GameControl);
    }
}
GameConfig.init();